### ISSUE TITLE
Add people in quarantine after travelling in a risky region

### ISSUE THREAD

**Issue by d-qn** [rsalzer/COVID_19_BAG#2]
Hello,

thanks for this cleaned up dataset ! For the _current_isolated_ data, would it be possible and easy to add the count of people in quarantine after travelling in a region at risk (Anzahl zusätzlicher Personen in Quarantäne, die aus Risikoländern eingereist sind)? These counts are typically much higher than the number of people in quarantine after being in contact with somebody tested positive.

Thank you advance. Best

**Comment by rsalzer** [comment]
Thanks for pointing that out. I havent checked for new data.
From today on the key _foreign_quarantined_ is included in _current_isolated_

https://github.com/rsalzer/COVID_19_BAG/commit/1e06bade98ec788f72a40504beb5d55cb27a968c
